In [1]:
import numpy as np

In [37]:
data = np.random.rand(4)

In [38]:
data

array([0.07726293, 0.2319879 , 0.57641478, 0.00262516])

In [39]:
data.ndim

1

In [40]:
data.shape

(4,)

In [41]:
data.T.shape

(4,)

In [42]:
data.T

array([0.07726293, 0.2319879 , 0.57641478, 0.00262516])

In [43]:
np.dot(data, data.T)

0.3920488323904412

In [44]:
# Python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))


C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


AttributeError: module 'tensorflow' has no attribute 'Session'

In [1]:
import numpy
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages

[[22. 28.]
 [49. 64.]]


In [1]:
import tensorflow as tf
tf.__version__

C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages

'1.14.0'

In [2]:
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))



In [3]:
import numpy
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
print(sess.run(c))

[[22. 28.]
 [49. 64.]]


In [4]:
import tensorflow as tf
hello = tf.constant('hello world')
sess = tf.Session()
sess.run(hello)

b'hello world'

In [6]:
with tf.device('/cpu:0'):
    a = tf.constant ([1.0, 2.0, 3.0], shape=[3], name='a')
    b = tf.constant ([1.0, 2.0, 3.0], shape=[3], name='b')

In [7]:
with tf.device('/gpu:1'):
    c = a + b

In [8]:
# 注意：allow_soft_placement=True表明：计算设备可自行选择，如果没有这个参数，会报错。
# 因为不是所有的操作都可以被放在GPU上，如果强行将无法放在GPU上的操作指定到GPU上，将会报错。
sess = tf.Session(config=tf.ConfigProto (allow_soft_placement=True, log_device_placement=True))
# sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
sess.run(tf.global_variables_initializer())
print (sess.run(c))

[2. 4. 6.]


In [9]:
import tensorflow as tf
hello=tf.constant(‘hello,world’)
sess=tf.Session()
print(sess.run(hello))

SyntaxError: invalid character in identifier (<ipython-input-9-830be9f3218e>, line 2)

In [10]:
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [11]:
Device mapping:

SyntaxError: invalid syntax (<ipython-input-11-a24c991017a0>, line 1)

In [3]:
# 规定程序使用的核心
import tensorflow as tf
import os

os.environ['CUDA_VISIBLE_DEVICES'] = "1"

In [4]:
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

In [5]:

#coding:utf-8

import tensorflow as tf

a=tf.constant([1.0,2.0,3.0],shape=[3],name='a')

b=tf.constant([1.0,2.0,3.0],shape=[3],name='b')

c=a+b

#log_device_placement=True 输出运行每一个运算的设备

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:

    print(sess.run(c))


[2. 4. 6.]


In [8]:



#coding:utf-8

import tensorflow as tf

with tf.device('/cpu:0'):

    a=tf.constant([1.0,2.0,3.0],shape=[3],name='a')

    b=tf.constant([1.0,2.0,3.0],shape=[3],name='b')

with tf.device('/gpu:0'):

    c=a+b

#log_device_placement=True 输出运行每一个运算的设备

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:

    print(sess.run(c))


InvalidArgumentError: Cannot assign a device for operation add_1: node add_1 (defined at <ipython-input-7-b449a3abe984>:16) was explicitly assigned to /device:GPU:1 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[add_1]]

Errors may have originated from an input operation.
Input Source operations connected to node add_1:
 a_2 (defined at <ipython-input-7-b449a3abe984>:10)	
 b_2 (defined at <ipython-input-7-b449a3abe984>:12)

In [9]:

a_cpu=tf.Variable(0,name='a_cpu')

with tf.device('/gpu:0'):

    a_gpu=tf.Variable(0,name='a_gpu')

with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:

    print(sess.run(tf.global_variables_initializer()))


InvalidArgumentError: Cannot assign a device for operation add_1: node add_1 (defined at <ipython-input-7-b449a3abe984>:16) was explicitly assigned to /device:GPU:1 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[add_1]]

Errors may have originated from an input operation.
Input Source operations connected to node add_1:
 a_2 (defined at <ipython-input-7-b449a3abe984>:10)	
 b_2 (defined at <ipython-input-7-b449a3abe984>:12)

In [1]:

import tensorflow as tf

import os

def set_config():

    # 控制使用率

    os.environ['CUDA_VISIBLE_DEVICES'] = '1'

    # 假如有16GB的显存并使用其中的8GB:

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)

    config = tf.ConfigProto(gpu_options=gpu_options)

    # session = tf.Session(config=config)

    return config

 

if __name__ == '__main__':

    a = tf.constant([1.0, 2.0, 3.0], shape=[3], name='a')

    b = tf.constant([1.0, 2.0, 3.0], shape=[3], name='b')

 

    c = a + b

    cfg=set_config()

    with tf.Session(config=cfg) as sess:

        print(sess.run(c))


C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\dongy\Anaconda3\envs\tensorflow\lib\site-packages

[2. 4. 6.]
